### PR TITLE
Background service for sending data

### LINKED ISSUE #11: Run in Background
When a user sets "send data" to on, then the app should be able to run in the background.

When the app is sending data , then a notification should be visible in the notification bar.

When the user touches the notification, the app should open.

### PR DESCRIPTION
**Pull request by residuum**
This is an implementation of background services for sending the data.

Will fix #11 and #35 

Currently, NFC tags are not working, because the current method needs an activity.

### CODE REVIEW

**Comment by residuum** [comment]
Probably NFC tags will be left out, because the current code will start the activity on any detected NFC tag when reading it, and will override any other NFC tag application.

**Comment by residuum** [comment]
Once, the latest commit of SensorApps/Common compiles on jitpack.io (see https://github.com/jitpack/jitpack.io/issues/5063), I will include it in dependencies and merge to master.

**Comment by ricardoscholz** [comment]
Hi. I've been watching (and looking fwd for) this improvement for a while. Very excited here to test it. How do I download a version with this feature? Current version at F-Droid seem to be "0.3.0", from years ago... =(

**Comment by residuum** [comment]
Here you go: https://cloud.residuum.org/index.php/s/32FwWk6LiHXAZQE

**Comment by ricardoscholz** [comment]
Thanx! I've been trying to test it, but it seems this version is not sending any outbound messages at all. Is there something in my phone configurations I'm missing? Got back to F-Droid version and it's OK. Also tested my listener app on PC and connection, and both seem OK.

UPDATE: Just downloaded and installed again and its working now! o/ Cheers!

**Comment by residuum** [comment]
I have created a new release yesterday, it should appear in FDroid in the next days.

**Pull request merged**
